site_name: TanninNotes
repo_url: https://github.com/superbra1n/TanninNotes
repo_name: TanninNotes
site_description: 个人学习笔记
site_author: Tannin Rachel
copyright: Copyright©️Tannin Rachel
theme:
  name: material
  logo: 'https://tannin-1316822731.cos.ap-nanjing.myqcloud.com/head.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.extra
  - pymdownx.superfences


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
